**Welcome to Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,7,32,8])

In [3]:
myarr

array([ 3,  7, 32,  8])

In [7]:
myarr = np.array([3,7,32,8],np.int8)

In [8]:
myarr

array([ 3,  7, 32,  8], dtype=int8)

In [9]:
myarr.shape

(4,)

In [10]:
myarr.dtype

dtype('int8')

#Array Creation :Conversion from other Python structures

In [11]:
listarray = np.array([[1,2,3],[5,6,7],[0,3,4]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [0, 3, 4]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
zeros=np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng=np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,4,4)

In [21]:
lspace

array([1., 2., 3., 4.])

In [22]:
emp = np.empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56602523e-307, 6.23059386e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11258854e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 7.56602523e-307, 1.29061821e-306,
        1.11260348e-306, 9.34600963e-307, 7.56602523e-307],
       [8.34451079e-308, 1.33508761e-307, 1.33511562e-306,
        8.90103560e-307, 1.42410974e-306, 8.90029544e-307]])

In [24]:
ide = np.identity(4)

In [25]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
arr = np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr = arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr = arr.ravel()

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.shape

(99,)

In [36]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [37]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [38]:
ar = np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0)

array([12,  8,  9])

In [41]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [42]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.nbytes

36

In [48]:
one = np.array([1,3,4,634,2])

In [49]:
one.argmax()

3

In [50]:
one.argmin()

0

In [51]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
ar.argmin()

8

In [54]:
ar.argmax()

6

In [55]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [56]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [57]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [62]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [63]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [64]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [65]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [66]:
ar.sum()

29

In [67]:
ar.max()

7

In [68]:
ar.min()

0

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [71]:
type(np.where(ar>5))

tuple

In [72]:
np.count_nonzero(ar)

8

In [73]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [74]:
ar[1,2] = 0

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [78]:
import sys

In [80]:
py_ar = [0,4,55,2]

In [81]:
np_ar = np.array(py_ar)